//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso
    {
        public Curso()
        {
            this.Matriculas = new HashSet<Matricula>();
        }
    
        public int CursoID { get; set; }
        public string Nombre { get; set; }
        public int Creditos { get; set; }
    
        public virtual ICollection<Matricula> Matriculas { get; set; }
    }
}
